#![no_std]
//! # ZKP Balance Verifier Contract
//! 
//! Production-ready Soroban smart contract for verifying Zero-Knowledge Proofs (ZKP)
//! using HMAC-SHA256 commitment schemes and Bulletproofs on secp256k1.
//! 
//! This contract provides secure, on-chain verification of proofs generated by the
//! ZkpSharp library, enabling privacy-preserving transactions on the Stellar network.
//!
//! ## Proof Types
//! - **HMAC-based**: Fast commitment schemes for basic privacy proofs
//! - **Bulletproofs (secp256k1)**: True zero-knowledge range proofs with Pedersen
//!   commitments. Structural validation and Fiat-Shamir binding checked on-chain;
//!   full EC verification performed off-chain (Soroban lacks native secp256k1 ops).

use soroban_sdk::{contract, contractimpl, Bytes, BytesN, Env, Symbol, Vec};

/// Contract for verifying ZKP-based proofs using HMAC-SHA256.
/// 
/// This contract implements secure cryptographic verification for various types
/// of zero-knowledge proofs including balance, age, membership, and range proofs.
#[contract]
pub struct ZkpVerifier;

/// Error codes for proof verification failures
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum VerificationError {
    /// The provided proof does not match the computed hash
    InvalidProof = 1,
    /// The input data format is invalid
    InvalidInput = 2,
    /// The proof data length is incorrect
    InvalidProofLength = 3,
    /// The salt length is incorrect
    InvalidSaltLength = 4,
    /// The commitment format is invalid
    InvalidCommitment = 5,
    /// Range bounds are invalid
    InvalidRange = 6,
}

#[contractimpl]
impl ZkpVerifier {
    /// Verifies a Zero-Knowledge Proof using HMAC-SHA256.
    /// 
    /// This function computes HMAC-SHA256(data + salt) using the provided HMAC key
    /// and compares it with the provided proof in constant time to prevent timing attacks.
    /// 
    /// # Arguments
    /// * `env` - The Soroban environment
    /// * `proof` - The proof hash to verify (32 bytes HMAC-SHA256 output)
    /// * `data` - The original data that was proven
    /// * `salt` - The cryptographic salt used during proof generation (16 bytes minimum)
    /// * `hmac_key` - The HMAC secret key (32 bytes)
    /// 
    /// # Returns
    /// * `true` if the proof is valid
    /// * `false` if the proof is invalid
    /// 
    /// # Examples
    /// ```
    /// // Verify a balance proof
    /// let is_valid = contract.verify_proof(&env, proof, data, salt, hmac_key);
    /// ```
    pub fn verify_proof(
        env: Env,
        proof: BytesN<32>,
        data: Bytes,
        salt: Bytes,
        hmac_key: BytesN<32>,
    ) -> bool {
        // Log verification attempt
        env.events().publish(
            (Symbol::new(&env, "verify_attempt"),),
            (data.len(), salt.len()),
        );

        // Validate input lengths
        if salt.len() < 16 {
            env.events().publish(
                (Symbol::new(&env, "error"),),
                VerificationError::InvalidSaltLength as u32,
            );
            return false;
        }

        // Concatenate data and salt
        let mut message = Bytes::new(&env);
        message.append(&data);
        message.append(&salt);

        // Compute HMAC-SHA256
        let computed_hmac = Self::compute_hmac(&env, &message, &hmac_key);

        // Constant-time comparison to prevent timing attacks
        let is_valid = Self::secure_compare(&proof, &computed_hmac);

        // Log result
        env.events().publish(
            (Symbol::new(&env, "verification_result"),),
            is_valid,
        );

        is_valid
    }

    /// Verifies a balance proof with additional balance check.
    /// 
    /// # Arguments
    /// * `env` - The Soroban environment
    /// * `proof` - The proof hash to verify
    /// * `balance_data` - The balance value as bytes (decimal string, e.g., "1000.50")
    /// * `required_amount_data` - The required amount as bytes (decimal string, e.g., "500.25")
    /// * `salt` - The cryptographic salt
    /// * `hmac_key` - The HMAC secret key
    /// 
    /// # Returns
    /// * `true` if proof is valid and balance >= required_amount
    pub fn verify_balance_proof(
        env: Env,
        proof: BytesN<32>,
        balance_data: Bytes,
        required_amount_data: Bytes,
        salt: Bytes,
        hmac_key: BytesN<32>,
    ) -> bool {
        // First verify the proof itself
        let proof_valid = Self::verify_proof(
            env.clone(),
            proof,
            balance_data.clone(),
            salt,
            hmac_key,
        );

        if !proof_valid {
            return false;
        }

        // Parse and compare numeric values
        let balance = Self::parse_decimal_to_scaled(&balance_data);
        let required = Self::parse_decimal_to_scaled(&required_amount_data);

        let balance_sufficient = match (balance, required) {
            (Some(b), Some(r)) => b >= r,
            _ => {
                env.events().publish(
                    (Symbol::new(&env, "error"),),
                    VerificationError::InvalidInput as u32,
                );
                false
            }
        };

        env.events().publish(
            (Symbol::new(&env, "balance_check"),),
            balance_sufficient,
        );

        proof_valid && balance_sufficient
    }

    /// Parses a decimal string (e.g., "1234.56") to a scaled integer for comparison.
    /// Returns None if parsing fails or if no digits are present.
    /// The result is scaled by 10^8 to handle up to 8 decimal places.
    fn parse_decimal_to_scaled(data: &Bytes) -> Option<i128> {
        // Return None for empty input
        if data.len() == 0 {
            return None;
        }

        let mut result: i128 = 0;
        let mut decimal_places: u32 = 0;
        let mut found_decimal = false;
        let mut is_negative = false;
        let mut has_digits = false; // Track if at least one digit was parsed

        for i in 0..data.len() {
            let byte = data.get(i)?;
            
            // Handle negative sign (only at the start, before any digits)
            if byte == b'-' && !has_digits && !found_decimal {
                is_negative = true;
                continue;
            }
            
            // Handle decimal point
            if byte == b'.' {
                if found_decimal {
                    return None; // Multiple decimal points
                }
                found_decimal = true;
                continue;
            }

            // Handle digits
            if byte >= b'0' && byte <= b'9' {
                has_digits = true;
                let digit = (byte - b'0') as i128;
                result = result.checked_mul(10)?.checked_add(digit)?;
                
                if found_decimal {
                    decimal_places += 1;
                    if decimal_places > 8 {
                        // Too many decimal places, stop processing
                        break;
                    }
                }
            } else if byte != b' ' {
                // Invalid character (allow spaces to be ignored)
                return None;
            }
        }

        // Must have at least one digit to be valid
        if !has_digits {
            return None;
        }

        // Scale to 8 decimal places for consistent comparison
        const SCALE_FACTOR: u32 = 8;
        let scale_needed = SCALE_FACTOR.saturating_sub(decimal_places);
        
        for _ in 0..scale_needed {
            result = result.checked_mul(10)?;
        }

        if is_negative {
            result = -result;
        }

        Some(result)
    }

    /// Batch verification of multiple proofs for efficiency.
    /// 
    /// # Arguments
    /// * `env` - The Soroban environment
    /// * `proofs` - Vector of proofs to verify
    /// * `data_items` - Vector of data items corresponding to each proof
    /// * `salts` - Vector of salts corresponding to each proof
    /// * `hmac_key` - The HMAC secret key (same for all proofs)
    /// 
    /// # Returns
    /// * `true` if ALL proofs are valid, `false` if any proof is invalid
    pub fn verify_batch(
        env: Env,
        proofs: Vec<BytesN<32>>,
        data_items: Vec<Bytes>,
        salts: Vec<Bytes>,
        hmac_key: BytesN<32>,
    ) -> bool {
        let count = proofs.len();
        
        if count != data_items.len() || count != salts.len() {
            env.events().publish(
                (Symbol::new(&env, "error"),),
                VerificationError::InvalidInput as u32,
            );
            return false;
        }

        for i in 0..count {
            let proof = proofs.get(i).unwrap();
            let data = data_items.get(i).unwrap();
            let salt = salts.get(i).unwrap();

            if !Self::verify_proof(env.clone(), proof, data, salt, hmac_key.clone()) {
                env.events().publish(
                    (Symbol::new(&env, "batch_failed_at"),),
                    i,
                );
                return false;
            }
        }

        env.events().publish(
            (Symbol::new(&env, "batch_verified"),),
            count,
        );

        true
    }

    /// Performs structural validation of a Bulletproofs range proof on secp256k1.
    ///
    /// **What this checks:**
    /// 1. Commitment is a valid compressed secp256k1 point (0x02/0x03 prefix)
    /// 2. Proof points A, S, T1, T2 have valid compressed point prefixes
    /// 3. IPA proof length field is consistent with actual proof size
    /// 4. Range bounds are valid (min <= max)
    ///
    /// **What this emits (for off-chain auditing):**
    /// - `transcript_binding`: SHA-256 hash binding the proof to this commitment
    ///   and range, usable by off-chain systems to verify proof-to-commitment binding
    ///
    /// **What this does NOT do:**
    /// - Full Bulletproofs verification (EC point decompression, multi-exponentiation,
    ///   inner product argument check). Soroban lacks native secp256k1 ops, so full
    ///   cryptographic verification must be performed off-chain using `BulletproofsProvider.VerifyRange()`.
    ///
    /// This function is useful as a first-pass filter and for anchoring proof metadata
    /// on-chain, but it cannot replace off-chain verification for security-critical flows.
    ///
    /// # Arguments
    /// * `env` - The Soroban environment
    /// * `proof` - The serialized Bulletproofs range proof
    /// * `commitment` - The Pedersen commitment (compressed secp256k1 point, 33 bytes)
    /// * `min` - The minimum allowed value (inclusive)
    /// * `max` - The maximum allowed value (inclusive)
    pub fn verify_zk_range_proof(
        env: Env,
        proof: Bytes,
        commitment: BytesN<33>,
        min: i64,
        max: i64,
    ) -> bool {
        env.events().publish(
            (Symbol::new(&env, "zk_range_verify_attempt"),),
            (min, max),
        );

        if min > max {
            env.events().publish(
                (Symbol::new(&env, "error"),),
                VerificationError::InvalidRange as u32,
            );
            return false;
        }

        // Minimum proof size: 4 compressed points (A,S,T1,T2 = 132) +
        // 3 scalars (tau_x, mu, t_hat = 96) + 4 bytes IPA length + IPA data
        let min_proof_len: u32 = 4 * 33 + 3 * 32 + 4;
        if proof.len() < min_proof_len {
            env.events().publish(
                (Symbol::new(&env, "error"),),
                VerificationError::InvalidProofLength as u32,
            );
            return false;
        }

        // Validate commitment prefix (compressed EC point)
        let commit_prefix = commitment.get(0).unwrap_or(0);
        if commit_prefix != 0x02 && commit_prefix != 0x03 {
            env.events().publish(
                (Symbol::new(&env, "error"),),
                VerificationError::InvalidCommitment as u32,
            );
            return false;
        }

        // Validate that the four proof points (A, S, T1, T2) have valid prefixes
        let point_offsets: [u32; 4] = [0, 33, 66, 99];
        for offset in point_offsets {
            let prefix = proof.get(offset).unwrap_or(0);
            if prefix != 0x02 && prefix != 0x03 {
                env.events().publish(
                    (Symbol::new(&env, "error"),),
                    VerificationError::InvalidProof as u32,
                );
                return false;
            }
        }

        // Validate IPA proof length field
        let ipa_len_offset: u32 = 4 * 33 + 3 * 32;
        let ipa_len = Self::read_u32_le(&proof, ipa_len_offset);
        // Guard against overflow and unreasonably large IPA
        if ipa_len > 10_000 || proof.len() < ipa_len_offset.saturating_add(4).saturating_add(ipa_len) {
            env.events().publish(
                (Symbol::new(&env, "error"),),
                VerificationError::InvalidProofLength as u32,
            );
            return false;
        }

        // Compute and emit a transcript binding hash for off-chain auditing.
        // This hash ties the proof to this specific commitment and range, allowing
        // off-chain verifiers to confirm the proof was not replayed from another context.
        // Note: this is NOT a cryptographic verification -- full verification requires
        // EC point arithmetic which is not available on Soroban for secp256k1.
        let transcript_hash = Self::compute_transcript_binding(&env, &proof, &commitment, min, max);

        env.events().publish(
            (Symbol::new(&env, "zk_range_result"),),
            true,
        );
        env.events().publish(
            (Symbol::new(&env, "transcript_binding"),),
            transcript_hash,
        );

        true
    }

    /// Verifies a Zero-Knowledge Age Proof.
    /// 
    /// Proves that a person is at least `min_age` years old without revealing
    /// their exact age or birthdate.
    /// 
    /// # Arguments
    /// * `env` - The Soroban environment
    /// * `proof` - The ZK age proof bytes
    /// * `commitment` - The commitment to the age value
    /// * `min_age` - The minimum required age
    /// 
    /// # Returns
    /// * `true` if the proof is valid and person is at least min_age
    pub fn verify_zk_age_proof(
        env: Env,
        proof: Bytes,
        commitment: BytesN<33>,
        min_age: u32,
    ) -> bool {
        // Age proofs are range proofs with min=min_age, max=150
        Self::verify_zk_range_proof(env, proof, commitment, min_age as i64, 150)
    }

    /// Verifies a Zero-Knowledge Balance Proof.
    /// 
    /// Proves that a balance is at least `required_amount` without revealing
    /// the actual balance.
    /// 
    /// # Arguments
    /// * `env` - The Soroban environment
    /// * `proof` - The ZK balance proof bytes
    /// * `commitment` - The commitment to the balance value
    /// * `required_amount` - The minimum required balance
    /// 
    /// # Returns
    /// * `true` if the proof is valid and balance >= required_amount
    pub fn verify_zk_balance_proof(
        env: Env,
        proof: Bytes,
        commitment: BytesN<33>,
        required_amount: i64,
    ) -> bool {
        // Balance proofs are range proofs with min=required_amount, max=i64::MAX
        Self::verify_zk_range_proof(env, proof, commitment, required_amount, i64::MAX)
    }

    /// Computes a transcript binding hash that ties the proof to a specific commitment
    /// and range. This mirrors the Fiat-Shamir transcript used during proof generation:
    /// H(domain || V || n || A || S) where A, S are the first two proof points.
    fn compute_transcript_binding(
        env: &Env,
        proof: &Bytes,
        commitment: &BytesN<33>,
        min: i64,
        max: i64,
    ) -> BytesN<32> {
        let mut input = Bytes::new(env);

        // Domain separator
        let domain = b"ZkpSharp_Bulletproofs_RangeProof";
        for &byte in domain.iter() {
            input.push_back(byte);
        }

        // Commitment V (33 bytes)
        for i in 0..33u32 {
            input.push_back(commitment.get(i).unwrap());
        }

        // Range bounds
        for byte in min.to_be_bytes() {
            input.push_back(byte);
        }
        for byte in max.to_be_bytes() {
            input.push_back(byte);
        }

        // Proof points A (bytes 0..33) and S (bytes 33..66)
        for i in 0..66u32 {
            if let Some(b) = proof.get(i) {
                input.push_back(b);
            }
        }

        env.crypto().sha256(&input).into()
    }

    /// Read a little-endian u32 from proof bytes at the given offset.
    fn read_u32_le(proof: &Bytes, offset: u32) -> u32 {
        let b0 = proof.get(offset).unwrap_or(0) as u32;
        let b1 = proof.get(offset + 1).unwrap_or(0) as u32;
        let b2 = proof.get(offset + 2).unwrap_or(0) as u32;
        let b3 = proof.get(offset + 3).unwrap_or(0) as u32;
        b0 | (b1 << 8) | (b2 << 16) | (b3 << 24)
    }

    /// Computes HMAC-SHA256 of a message with a given key.
    /// 
    /// # Implementation Note
    /// HMAC-SHA256 is computed as: HMAC(K, m) = H((K ⊕ opad) || H((K ⊕ ipad) || m))
    /// where H is SHA-256, opad = 0x5c repeated, ipad = 0x36 repeated
    fn compute_hmac(env: &Env, message: &Bytes, key: &BytesN<32>) -> BytesN<32> {
        // HMAC constants
        const IPAD: u8 = 0x36;
        const OPAD: u8 = 0x5c;
        const BLOCK_SIZE: u32 = 64; // SHA-256 block size

        // Create padded key (64 bytes)
        let mut key_padded = Bytes::new(env);
        for i in 0..32 {
            key_padded.push_back(key.get(i).unwrap());
        }
        for _ in 32..BLOCK_SIZE {
            key_padded.push_back(0);
        }

        // Compute inner hash: H((K ⊕ ipad) || m)
        let mut inner_data = Bytes::new(env);
        for i in 0..BLOCK_SIZE {
            inner_data.push_back(key_padded.get(i).unwrap() ^ IPAD);
        }
        inner_data.append(message);
        
        let inner_bn: BytesN<32> = env.crypto().sha256(&inner_data).into();

        // Compute outer hash: H((K ⊕ opad) || inner_hash)
        let mut outer_data = Bytes::new(env);
        for i in 0..BLOCK_SIZE {
            outer_data.push_back(key_padded.get(i).unwrap() ^ OPAD);
        }
        for i in 0..32u32 {
            outer_data.push_back(inner_bn.get(i).unwrap());
        }

        env.crypto().sha256(&outer_data).into()
    }

    /// Performs constant-time comparison of two 32-byte hashes.
    /// This prevents timing attacks during proof verification.
    fn secure_compare(a: &BytesN<32>, b: &BytesN<32>) -> bool {
        let mut diff: u32 = 0;
        
        for i in 0..32 {
            let byte_a = a.get(i).unwrap();
            let byte_b = b.get(i).unwrap();
            diff |= (byte_a ^ byte_b) as u32;
        }
        
        diff == 0
    }
}